server:
  port: 8080
  
---
spring:
  profiles: local-mssql
  datasource:
    url: jdbc:mysql://localhost:3306/aviation?useSSL=false
    username: root
    password: root
 
---
server:
  context-path: /
---
spring:
  jpa:
    properties:
      hibernate.dialect:
        org.hibernate.dialect.MySQL5Dialect
---
spring:
  datasource:
    url:
      jdbc:mysql://localhost:3306/aviation?useSSL=false
